### ISSUE TITLE
[BOUNDARY ERRATA] AUS ADM2 - Water Boundaries

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1338]
**Describe the Error**
AUS ADM2 has water boundaries included; as we represent terrestrial boundaries we need to remove these.

**Screenshots**
![image](https://user-images.githubusercontent.com/7882645/117990734-6e365a00-b30b-11eb-9314-ada2e463fdb0.png)

**Comment by MichaelR-geoLab** [comment]
This will be fixed by another AUS ADM2 issue

**Comment by mmyrte** [comment]
This was, in fact, not fixed by #1581 - it only fixed #1169.

If someone (me? aah, but the time, the time...) should make a PR: the data source changed to https://data.gov.au/data/dataset/geoscape-administrative-boundaries (was https://data.gov.au/dataset/psma-administrative-boundaries).

The new license they're using is CCBY 4.0; that should be compatible, right?
