### ISSUE TITLE
HPSCU and HPSCGS Finer Resolution Boundary issues

### ISSUE THREAD

**Issue by samapriya** [wmgeolab/geoBoundaries#1574]
Hi there,
If I understand correctly the HPSCU boundaries are supposed to be the premier finer version of global country boundaries am I right but I just compared, for example, HPSCU Russia and HPSCGS Boundary, and the HPSCGS boundary look much finer with more details. Am I interpreting this wrong? Including the screengrab. Any thoughts and suggestions would be appreciated here
![boundary_compare](https://user-images.githubusercontent.com/6677629/125153269-2324a180-e118-11eb-8f51-afe5f91f27fd.gif)

**Comment by maxmalynowsky** [comment]
Hi Samapriya, for sources coming from OpenStreetMap (like the one above), OSM boundaries around coastlines are extended into the water to help with data management, since coastlines are managed as a separate layer there. It's also common for countries like the US and Canada to offer their official boundary datasets with generalized coastlines for the same reason, with an example of that here: https://www150.statcan.gc.ca/n1/pub/92-195-x/2011001/other-autre/carto-eng/carto-eng.htm

The finer precision you're seeing here is a result of the original dataset being clipped with an ADM0 layer that has a defined coastline. If you visit OpenStreetMap, you'll see both coastlines and ADM0 represented separately:
<img width="1713" alt="Screen Shot 2021-07-11 at 20 47 48" src="https://user-images.githubusercontent.com/4202166/125206820-6ce0c980-e289-11eb-8b97-977d248e8fbd.png">

**Comment by samapriya** [comment]
Thank you, that makes sense, I am ingesting this dataset into Google Earth Engine right now so wanted to make sure I understood the data structure. I am making sure the attributions are present and I can update the ticket with the collection information once done. Appreciate your explanation am closing the ticket

**Comment by DanRunfola** [comment]
@samapriya Just FYSA, we are right on the cusp of pushing our 4.0 product out more formally (which will include all of the QA'd files in this repo, as well as a new / more responsive API, and much better licenses across the board).  I'd estimate end-of-July / early-Aug right now.
