### ISSUE TITLE
[BOUNDARY ERRATA] - CGAZ-ADM0 sliver

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1577]
Hey guys I know alot of processing has changed in preparation for v4 in the CGAZ, but wanted to point out an issue in case it is unknown.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/23552439/125316768-6d6b7580-e306-11eb-94cc-529ae4b7877b.png)

Here is a place where Spain (ESP-ADM0-3_0_0-B1), Andora (AND-ADM0-3_0_0-B1), and France (FRA-ADM0-3_0_0-B1) come together it looks like the process assigned empty gaps to France.

**Comment by DanRunfola** [comment]
Thanks for the report.  I believe FRA ADM0 has been updated so this may
become a non-issue, but in general there are going to be many issues like
this in the current CGAZ product due to how we gap fill (largest area
touching an enclosed gap).  Max is working on a new approach that should be
much better, and avoid issues like this.

**Comment by DanRunfola** [comment]
I am closing this, as the new CGAZ has many new issues we'll be working on fixing, but hopefully this won't be one of them :)
