### ISSUE TITLE
Store canonical names for administrative regions

### ISSUE THREAD

**Issue by charliejhadley** [wmgeolab/geoBoundaries#161]
geoBoundaries is an incredible resource and already extremely useful to me. However, there's a feature of the GADM dataset that I think would be well received by your users.

Often I'm asked to map a country I don't know well down to ADMn, but I don't know the canonical name given to each level - e.g. ADM4 of Belgium are either "Gemeente" or "Commune". It would then be useful to access the hierarchy of ADM names. eg for Belgium the levels are Region > Capital Region/Province/Provincie > Arrondissement > Commune/Gemeente.

However, I recognise that geoBoundaries prides itself on precision and consistency so if your data sources don't provide high enough quality assurance for this variable I fully support leaving it out.

**Comment by DanRunfola** [comment]
We are working on this!  The plan would be to release this information as a
part of our metadata for each boundary, so that it's easily referenced.  A
few issues that are emergent there:
1) Encoding is a little tricky in some cases.
2) We don't have the canonical names for everwhere - yet - so this is
likely a 5.0 target right now (maybe 4 if we get really lucky!).
3) How to handle disagreement of canonical names.  I don't think this is a
huge issue, but we'll want to come up with a clear procedure here - i.e.,
preferencing authoritative sources? Wikipedia?  Etc.

Disputed regions are also an interesting question here.

As I add this to the roadmap, any specific regions you might be interested
in us prioritizing?

Dan

**Comment by charliejhadley** [comment]
That’s awesome news, thanks! I’m going to keep track of how you implement this so I can offer a PR for the R wrapper to your service https://github.com/wmgeolab/rgeoboundaries

**Comment by DanRunfola** [comment]
Just a quick update on this - it looks like we'll have canonical for the majority of our cases in 4.0.0, which ETA is in the next few months (likely by July at the latest).  I'm going to close this out, but stay tuned.

Dan
