### ISSUE TITLE
OSM source credit? 

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1698]
**Describe the Error**

For the geoBoundaries sources that are based on OpenStreetMap, these are typically gathered from either the Wambacher site or the OSMBoundaries site. The ordering of these in the gb metadata however, lists OpenStreetMap as 'boundarySource-1' and Wambacher/OSMBoundaries as 'boundarySource-2'. Based on the description in [the guidelines](https://github.com/wmgeolab/geoBoundaries/blob/main/CONTRIBUTING.md), 'boundarySource-1' should list 'where did you get this data' which in this case is Wambacher/OSMBoundaries, and 'boundarySource-2' should list 'where did source 1 get this data' which would be 'OpenStreetMap'? 

I'm also not sure whether Wambacher/OSMBoundaries should even be considered a source, or if they should just be acknowleded in the 'boundarySourceURL'; I guess this depends on whether they are simply a data platform that extracts and makes it easier to download OSM data or if they also do some level of prepping/cleaning and can be considered a source?

**Comment by DanRunfola** [comment]
One of our big goals between 4 and 5.0 is actually to move away from OSM as
a source, both due to licensure (SA restrictions, which inhibits us from
producing gB as a single-licensure product) and accuracy concerns.  So -
agreed this is an issue, but probably not worth digging too far into as it
should be out of the db soon (tm).
