### ISSUE TITLE
[BOUNDARY ERRATA] NPL ADM0 required field error

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1700]
The new api returns ISO_Code instead of shapeISO for Nepal's ADM0.  I'm about to check and see if there are other similar issues in other countries.

**Comment by DanRunfola** [comment]
I don't think we ever returned shapeISO through the API (i.e., the API
always returned layer-level information, not shape-level information).

could you provide a link to the behavior your seeing?  It *definitely*
shouldn't be returning a "ISO_Code" object, if that's what it's doing (I
can't even figure how that would happen).

**Comment by leeberryman** [comment]
@DanRunfola yeah I'm sorry I wasn't clear.  I'm using the api to get to the underlying raw Git URL.  The ISO_Code is coming from the underlying shape file. 

https://github.com/wmgeolab/geoBoundaries/raw/59e24afc9c494ad8f2eae8ff0d9168c11bb03fb8/releaseData/gbOpen/NPL/ADM0/geoBoundaries-NPL-ADM0-all.zip

**Comment by DanRunfola** [comment]
oh - I see, in the attribute table of the shapefile itself.  Interesting.

Not sure why that isn't getting caught - I'll dig into this.  Must be an
error in the build somewhere.

**Comment by DanRunfola** [comment]
Ok - found this one and fixed it.

Because the ISO_CODE fields are named in many different ways, I have a hard-coded programmatic check to standardize.  We've gotten better over time at fixing this in our source data, but this was a permutation I hadn't caught before.  Line 424 of gbBuild.py in the bot is now:

isoC = set(['ISO', 'ISO_code', 'ISO_Code', 'ISO_CODE', 'iso', 'shapeISO', 'shapeiso', 'shape_iso']) 

Note that I leave "old" attribute information intentionally in the files, just in case things like this come up (i.e., I'd rather the user have the data than not).  One day it might be good to move away from that, but it'll take a lot more reports like this before I have confidence we've squashed all the bugs :). 

Closed by https://github.com/wmgeolab/geoBoundaryBot/commit/a7b37b254048e8d5bbe70df6fcd719cd2988ee01
