### ISSUE TITLE
[FEATURE REQUEST] metadata documentation

### ISSUE THREAD

**Issue by chapmanjacobd** [wmgeolab/geoBoundaries#1934]
The question that I am currently facing is whether to use `fid` or `shapeID`. Which one is more future-proof? Admin0 looks like it is missing some love because it doesn't have shapeID... or worse yet no shapeName :/

![image](https://user-images.githubusercontent.com/7908073/141394604-eca090fd-a3ec-45ca-a8b7-e635689eabce.png)

For me as a user it looks like these are the only meaningful pieces of data:

```
        "boundary_level": boundary["shapeType"].values[0],
        "iso_31661_a3": boundary["ISO_CODE"].values[0],
        "boundary_name": boundary["shapeName"].values[0],
        "boundary_id": boundary["shapeID"].values[0],
```

maybe the other null columns should be removed or consolidated...

By the way, GeoPackage might be a nicer release format in place of GeoJson. The spatial index makes the boundaries load much faster in QGIS and it is fast to convert from TopoJson with `ogr2ogr`:

```sh
ogr2ogr geoBoundariesCGAZ_ADM0.gpkg geoBoundariesCGAZ_ADM0.topojson
```

Additionally, this [random internet person](https://towardsdatascience.com/why-you-need-to-use-geopackage-files-instead-of-shapefile-or-geojson-7cb24fe56416) says GeoPackage might be a good format to use for "Handling Geography Masters" which I don't have experience with but it might be a good article to read if GeoPackage is less familiar to y'all 🤠 

Additionally, you might want to perform a similar operation as this (within the build system that you have) to make the metadata a little bit more consistent across different admin groups:

```
sqlite3 geoB_4.0.0_adm0.gpkg  alter table globalADM0 add column "shapeType" text;
sqlite3 geoB_4.0.0_adm0.gpkg  alter table globalADM0 add column "shapeName" text;
sqlite3 geoB_4.0.0_adm0.gpkg  alter table globalADM0 add column "shapeID" text;
sqlite3 geoB_4.0.0_adm0.gpkg  "SELECT load_extension('mod_spatialite');  update globalADM0 set "shapeType" = 'ADM0';"
sqlite3 geoB_4.0.0_adm0.gpkg  "SELECT load_extension('mod_spatialite');  update globalADM0 set "shapeID" = fid;"

sqlite3 geoB_4.0.0_adm1.gpkg  "SELECT load_extension('mod_spatialite');  update globalADM1 set "ISO_CODE" = "shapeGroup";"
sqlite3 geoB_4.0.0_adm2.gpkg  "SELECT load_extension('mod_spatialite');  update globalADM2 set "ISO_CODE" = "shapeGroup";"
```

**Comment by DanRunfola** [comment]
Hi Jacob,

First - we do have it on our list to include other file formats, but it will probably be a circa 5.0 thing.  The bigger issue isn't the technical on the back end (it's trivial to convert across formats), but rather the UI and accessibility for users on the front end.  If you're only referring to CGAZ, then this is something we could probably implement quicker.

Second - it looks like this is CGAZ, and what you're highlighting is a known error.  Essentially we aren't stripping everything properly at the end of our build (or identifying all of the correct name fields).  This will definitely be resolved in the next CGAZ update; see the interrelated issues over at https://github.com/wmgeolab/geoBoundaries/issues/1681 and https://github.com/wmgeolab/geoBoundaries/issues/1708 .

Third - on metadata - you're right!  We currently don't have metadata explicitly for CGAZ, which is something I want to leave this issue open for until we resolve.  

ETA on the above is "as soon as I have a breather", which is likely next semester as I'm teaching overloads at the moment due to some faculty leaving for industry :)

-Dan

**Comment by chapmanjacobd** [comment]
Hi Dan,

I appreciate the time you took to write a detailed response. I hope that university administration is treating you fairly :-)

Is the build script for CGAZ public? maybe I could try to fix some of these bugs via PR. I'm familiar with R and some python

-Jacob

**Comment by DanRunfola** [comment]
Help is always appreciated!

I just pushed the CGAZ code up - the push back with 4.0 had failed due to a file size constraint on the ISO0 boundaries, so that's now been corrected (never expected to enable gitLFS on the code repo :) ).   The script is here:
https://github.com/wmgeolab/geoBoundaryBot/blob/main/gbCGAZBuild.py

**plenty** of things that could be fixed there, so don't hesitate to rebuild to your hearts content.  Also, CGAZ is the only piece of the build that has to be run on a local machine due to memory restrictions on the side of the Azure runners, so testing locally is just fine.  Probably the easiest piece of code to edit in the entire gB stack!

**Comment by DanRunfola** [comment]
Huge thanks for the contributions to this - going to close this as per your contributions to https://github.com/wmgeolab/geoBoundaryBot/pull/4
