### ISSUE TITLE
[BOUNDARY ERRATA]: India Admin 0

### ISSUE THREAD

**Issue by chapmanjacobd** [wmgeolab/geoBoundaries#2237]
**Describe the Error**
India has MAX_Name but no shapeName 

https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/gbOpen/IND/ADM0/geoBoundaries-IND-ADM0.topojson

**Screenshots**
![image](https://user-images.githubusercontent.com/7908073/162503044-02a9e4f2-bd41-46bb-afb0-88d2fed66956.png)

**Comment by chapmanjacobd** [comment]
also Nepal is all uppercase... NEPAL

**Comment by DanRunfola** [comment]
@heatherbaier We've seen two issues with shapeName in the last day (see also an issue in AFG https://github.com/wmgeolab/geoBoundaries/issues/2236 ) - can you chase this down?

**Comment by chapmanjacobd** [comment]
would it be of any interest to have a lightweight PR check bot which can check new or modified geometries to make sure they have shapeName and shapeGroup ? if it is useful we can add more properties in the future but I think those are the most important attributes that must have consistency. 

Which file type is usually edited ? shapefile, geojson, topojson? which one is the "source of truth"? Are they all updated in every PR?

BTW... have you thought about putting almost all the files larger than a ~100 KB into LFS? It might be faster to work across git commits that way; maybe there is a way to keep all the metadata files in git and all the data files into LFS? Or maybe [the way I'm checking out](https://github.com/chapmanjacobd/geoBoundaries/blob/chapmanjacobd-patch-1/.github/workflows/zPR_Check.yml) `HEAD^` is wrong (it downloads ~18 GB which takes 17mins in Github Actions and then I think the Github Actions runs out of space   `Error: error: unable to write file releaseData/gbOpen/MEX/ADM2/geoBoundaries-MEX-ADM2.shp`)

**Comment by DanRunfola** [comment]
PRs are *always* appreciated :).  The checks would be easy enough to add in (or, alternatively, if a shapeName column doesn't exist, add an empty one) - that all happens around line 419 here: https://github.com/wmgeolab/geoBoundaryBot/blob/main/gbBuild.py .  The shapeGroup piece happens later, around line 441.  It should be pretty straightforward to do the logic for the checks.

All of the files are written simultaneously - line 464 of that script.

Right now we have everything > ~100mb on git LFS, this is mostly due to cost considerations (Github bills I/O off of LFS, and we end up in the terrabytes range most months as is).  If we were to migrate to LFS, I might do it in totality - i.e., just have all the files on LFS - but that would require a bit of re-engineering across a few different files (especially the API links would need to be checked).  

If you're using github actions and trying to clone the head, it *should* fit, but if not you can also do shallow clones (which is how I do it on our actions - see https://github.com/wmgeolab/geoBoundaries/blob/main/.github/workflows/yDISPATCH_gBLayer.yml for an example):

git clone --filter=blob:none --no-checkout https://github.com/wmgeolab/geoBoundaries
           echo "=============="
           cd geoBoundaries
           echo "=============="
           git sparse-checkout set "sourceData/${{github.event.inputs.bType}}/${{github.event.inputs.ISO}}_${{github.event.inputs.ADM}}.zip"
           git sparse-checkout add ".gitattributes"
           git sparse-checkout add ".gitignore"
           git sparse-checkout add "releaseData/${{github.event.inputs.bType}}/${{github.event.inputs.ISO}}/${{github.event.inputs.ADM}}/"
           git checkout

**Comment by chapmanjacobd** [comment]
very helpful Dan

The partial clone strategy will probably resolve all my problems

you might be able to use git-annex instead of git lfs to save costs. with git-annex you have more control over the storage backend. Another advantage is that the files are not duplicated in your checkout. With LFS, lfs files are present as git objects both in .git/lfs/objects and in your working repository. So If you have 20 GB of LFS files, you need 40 GB on your disk. While with git annex, files are symlinked so in this case only 20 GB is required.

- https://git-annex.branchable.com/walkthrough/
- https://www.reddit.com/r/DataHoarder/comments/j3jaz3/gitannex_in_2020/

Another option would be to consolidate the file types that are offered. Shapefile does not support topology. GeoJson seems like a duplicated offering because TopoJson is offered. FlatGeoBuf is a great format space and performance-wise. You might consider using only FlatGeoBuf and TopoJson in this repo, and moving the simplified outputs and shapefile options to only exist on a website or another repo. That should help with the size of this repo. If you did this you would need to use TopoJson with mapshaper because it doesn't support FlatGeoBuf yet.

**Comment by DanRunfola** [comment]
@chapmanjacobd Apologies on just now catching this, it never popped in my email.  

My understanding is the advantage of git LFS is that it plays nicely with revision history; I'll take a look at annex as we can, though.

On file types - yes, we definitely have redundancy, but we also want to ensure that any community can use the data.  Many users can't deal with topojsons yet, shapefiles are the industry standard (like it or not), and I hate shapefiles so personally use geojson when I can't use topo :).  

My actual goal here is to try and get some time with a github engineer and plumb through the best ways to improve effeciency without having to lose any of the revision history or related files.  From some sidebar chats it sounds like there are plenty of enormous "monorepository" strategies, we just need to really put some thought into which one is best for us.

**Comment by DanRunfola** [comment]
Correcting this with https://github.com/wmgeolab/geoBoundaries/pull/2813 - should be in the DB this week.
