### ISSUE TITLE
4.0.0 release archives corrupt (.zip and .tar.gz)

### ISSUE THREAD

**Issue by marcusj** [wmgeolab/geoBoundaries#2365]
Tried several times from different locations on different machines to download the 4.0.0 release archive files in both .zip and .tar.gz formats.  Both are coming up as truncated.  The .zip was 3.4GB downloaded and the .tar.gz was 2.7GB.

**Comment by DanRunfola** [comment]
Just to make sure - you're talking about the releases on github here, right? 

https://github.com/wmgeolab/geoBoundaries/releases

Those are automatically generated by GitHub, and I can download them on my linux box.  What program are you using to open the files?

**Comment by marcusj** [comment]
Yes, those releases. Infozip unzip and Mac OS tar.

**Comment by DanRunfola** [comment]
Alright - I just checked this as well, and am also getting an unexpected End-of-file with:
```
tar -xvzf geoBoundaries-4.0.0.tar.gz
```

It gets to around CHN before erroring out.

For the short term, all files from 4.0 can be indivdually downloaded by browsing the commit here:
https://github.com/wmgeolab/geoBoundaries/tree/193f7f6381b022580acf99ec40b1b9ade79f5934

But, I am going to have to raise this via Github itself, since I don't control the actual archive being built.  It will probably take them a while to get back to us (though they have been helpful in the past), so I'm going to close this for now since there's at least a workable solution to getting the data.  Frustrating!

**Comment by DanRunfola** [comment]
Just to follow up on this, I did receive a response from github.  Not sure it helps us much, but for the record :) 

Hey Dan,

Thanks for writing in to GitHub Support!

First, I'm truly sorry for the incredibly belated nature of this reply! We would certainly have wished to get back to you sooner. bow

I've been able to easily replicate this. According to [our documentation](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas):

Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

Since I don't believe that to be the case here (individual files larger than 2 GB), I've gone ahead and escalated your query to the relevant team.

While we don't yet have an ETA, we'll be sure to respond once there's news to share.

Meanwhile, please feel free reach out with any additional questions you might have about this.

Best regards,

Allan H

GitHub Support
