### ISSUE TITLE
Missing CGAZ .zips

### ISSUE THREAD

**Issue by LangsterGA** [wmgeolab/geoBoundaries#2661]
You have broken links to the 'CGAZ' folder for the shapefiles section of download on the page below. The links are to the '.zip' files for the Administrative boundary shapefiles. Just a suggestion to include the task of generating zip files for the administrative shapefiles as part of your nightly automated updates to this folder. Or, to update your website's broken links.

https://www.geoboundaries.org/downloadCGAZ.html

**Comment by DanRunfola** [comment]
Ack, this is due to the shift to Git LFS for all files.  Five minutes and it'll be fixed, will report back here.

New website is coming soon!

**Comment by DanRunfola** [comment]
Links are now fixed.

This is actually a deeper seated issue with our new nightly build routines going live with 5.0 - I had previously manually built CGAZ due to memory limitations on the cloud nodes.  With the local nodes doing the building, that's no longer an issue so CGAZ can be automated, but the manual zipping of the shapefile from the old process wasn't fixed :) :).  I'm going to leave this open as a reminder, hope to get it wrapped in shortly.

Also note the CGAZ website is erroneous in that it states the build it was constructed from is outdated by ~2 years - it's now live / in-step with the rest of geoBoundaries.  Not going to bother fixing it as I hope our new site will be live in the next week or so!

**Comment by LangsterGA** [comment]
Thanks so much! I am excited for the new website too.

**Comment by DanRunfola** [comment]
Fixed by https://github.com/wmgeolab/geoBoundaryBot/commit/4697f83f15085e320040920a42f2e5157ab1e722 - running a "nightly" tonight to confirm before I turn the nightlies back on so they're running each day.

**Comment by DanRunfola** [comment]
Just confirming this is now fixed, and *zip files are built in the nightly.

**Comment by LangsterGA** [comment]
Awesome - thanks!
