### ISSUE TITLE
[BOUNDARY ERRATA] Flanders Belgium

### ISSUE THREAD

**Issue by Portur** [wmgeolab/geoBoundaries#3194]
**Describe the Error**
Data quality

fid 306
shapeID 27649430B69989386836371
shapeType ADM1

**Screenshots**
Actual
![image](https://github.com/wmgeolab/geoBoundaries/assets/24350810/96177d11-9d86-470c-9b31-4bd0fa544b9c)

Expected
![image](https://github.com/wmgeolab/geoBoundaries/assets/24350810/919e2a74-719a-45d8-b01b-925063e5819e)

**Additional context**
Have a great day 🌻

**Comment by DanRunfola** [comment]
@Portur It looks like you're using CGAZ, which is a simplified product we provide for global synopses; it is by design less accurate than our individual country files.  Just FYI!  You can see an example of the simplification on the site - https://www.geoboundaries.org/simplifiedDownloads.html

That said, in this case our source is also pretty low granularity, so using the country-specific files would _help_, but not really solve the error.

![image](https://github.com/wmgeolab/geoBoundaries/assets/7882645/9c0b3967-0cd1-47e6-8b43-729f68f20c4d)

Thus, @jingjli1 we should dig into this.  I'd imagine that there is something out there given we've had a lot of success with other EU countries, which (as I understand it) are formally required to release this information.  It just seems to vary significantly re: how easy it is to find the files.

**Comment by Portur** [comment]
I could help with boundary data to improve accuracy and consistency? It's all from OSM but I somewhat automated with some javascript

**Comment by Portur** [comment]
Should I leave some feedback here?

I am familiar with github and postgres so I don't mind making a PR. Typically I try to stay away from shapefile wherever possible but I could put something together if needed. Otherwise ideally I could share a pg_dump file. 

I also don't mind starting up a postgres db which you can connect to and pull data as you see fit.

**Comment by DanRunfola** [comment]
The pull request model is the one we're most ready to integrate with - our format is pretty strict, as there is a QA/QC check that automatically occurs.  See, for example, this PR:
https://github.com/wmgeolab/geoBoundaries/pull/3188

We only accept PRs that pass all checks (automatic), have only one file changed in the sourceData folder, and the zip file uploaded must have the same format as the one in that PR.  There's a bit more detail here: https://github.com/wmgeolab/geoBoundaries/blob/main/CONTRIBUTING.md

(Seperately, we have a huge backlog of PRs I'm just noticing, so going to work on that shortly.  One of our automated scripts gone wild I think!).

**Comment by Portur** [comment]
Ah ok, I'll take a look

**Comment by BrentWHR** [comment]
>Thus, @jingjli1 we should dig into this. I'd imagine that there is something out there given we've had a lot of success with other EU countries, which (as I understand it) are formally required to release this information. It just seems to vary significantly re: how easy it is to find the files.

I previously found a seemingly suitable file for BEL and reported it here #2829 it only needs some spatial processing to get it to ADM0. There is an updated version for 2023 now too but I have not looked into this file yet: https://statbel.fgov.be/en/open-data/statistical-sectors-2023

When looking for Belgian data before I found that it was usually either just Flanders or just Walloon, hardly every for the whole country.

**Comment by 11helenab** [comment]
Closed, Pull Request #4160
