### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [wmgeolab/geoBoundaries#3216]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/wmgeolab/geoBoundaries/assets/147402107/731d4774-a91e-4116-8db8-eedea1c5b078)

**Comment by Kalyanimhala** [comment]
@DanRunfola Kindly assign me this issue, I want to work on it. Thank You!

**Comment by DanRunfola** [comment]
Hi there - we track contributors here:
https://github.com/wmgeolab/geoBoundaries/graphs/contributors

We have previously had a contributors section in our index, and made the decision to stop due to some fairly regularly bugs/errors cropping up.  We're a lean team, so anything that adds overhead and is redundant is not something we're interested in pursuing at this time.
