### ISSUE TITLE
US Congressional Districts

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#47]
The United States Congressional Districts pose an interesting case because they don't necessarily align with the other ADMs in all cases, yet they serve as an important administrative division, especially when examining the country at a federal level. Thus, further research is needed to determine whether or not geoBoundaries should include these districts as a US ADM in the next release.

**Comment by DanRunfola** [comment]
I would welcome comments on this - traditionally, gB is designed to cover governmental administrative zones - i.e., a region that an elected or otherwise ruling party asserts control over.  In some cases, these zones may not align with the zones that are used to elect those officials.  I am torn as to if we should go down the path of adding these types of boundaries; my instinct is to potentially aim to release another product along the lines of "global voting zones", building on the work of UMD's GMED (https://sites.google.com/site/joelsawatselway/PROJECTS/global-mapping-of-electoral-districts-gmed).

**Comment by dickoa** [comment]
I think another product will probably be less confusing. As an example, I had similar discussions with OCHA to include Nigeria Senatorial districts into the Nigeria common operational admin boundaries data (COD-AB). This layer was used for the regional food security assessment at the time. It's now in the global Nigeria COD-AB but not part of hierarchy adm0-adm3.

https://data.humdata.org/dataset/nga-administrative-boundaries

**Comment by DanRunfola** [comment]
I previously had discussions with UMD about potentially hosting the GMED product; I could potentially start a broader conversation with them.  I do want to be a little careful about having geoBoundaries grow beyond it's original scope, though - ADMs are hard enough :).

That said, I could imagine something like "geoBoundaries Ancillary", which are less-frequently-updated products like this that could be of benefit to researchers.  They would be more in the realm of "one-off-products".  That would let us reveal them via the API though, which could be useful (i.e., via the new TYP flag that's used to toggle to CGAZ, or will be used for hierarchy lookups).

**Comment by DanRunfola** [comment]
Alright, putting this one on the backburner for now as we clean up in prep for 4.0 / 5.0.  Likely going to be a while before we can engage with ancillary data.  Keeping this open, but tagging for 5.0 at the earliest, probably slipping to 6.
